FROM quay.io/centos/centos:stream9

WORKDIR /home/coder
USER root
RUN yum -y clean all && yum -y update
RUN yum -y install epel-release
RUN yum -y install wget gcc htop man nano vim emacs vim-common less tree zip unrar-free p7zip p7zip-plugins iputils dnsutils graphviz \
        openssh-clients jq wireshark-cli openssl-devel bzip2-devel libffi-devel snappy lz4-devel python3-pip bsdtar zlib-devel pylint nodejs \
        tmux unzip dirmngr gnupg ca-certificates yarnpkg ghostscript cmake 
RUN yum -y groupinstall "Development Tools"

# Python 3.11 Install
RUN cd /usr/src \
        && wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz \
        && tar -xzf Python-3.11.4.tgz \
        && cd Python-3.11.4 \
        && ./configure --enable-optimizations \
        && make altinstall

RUN update-alternatives --install /usr/bin/python python /usr/local/bin/python3.11 20

# Python 3.10 Install
RUN cd /usr/src \
        && wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz \
        && tar -xzf Python-3.10.12.tgz \
        && cd Python-3.10.12 \
        && ./configure --enable-optimizations \
        && make altinstall

# Code-Server Install
RUN mkdir -p ~/.local/lib ~/.local/bin
RUN curl -fL https://github.com/coder/code-server/releases/download/v4.14.1/code-server-4.14.1-linux-amd64.tar.gz \
        | tar -C ~/.local/lib -xz
RUN mv ~/.local/lib/code-server-4.14.1-linux-amd64 ~/.local/lib/code-server-4.14.1
RUN ln -s ~/.local/lib/code-server-4.14.1/bin/code-server ~/.local/bin/code-server
ENV PATH="~/.local/bin:$PATH"

# PIP Installs
RUN pip install jupyter jupyterhub ipywidgets widgetsnbextension jupyterlab-git s3cmd pylint s3transfer dotbot yara
